#!/usr/bin/env bash

_PLATFORM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
_REPO_ROOT="$(cd "${_PLATFORM_DIR}/../.." && pwd)"

export NEMOTRON_PLATFORM="${NEMOTRON_PLATFORM:-rtx5090}"
export NEMOTRON_REPO_ROOT="${NEMOTRON_REPO_ROOT:-${_REPO_ROOT}}"
export NEMOTRON_VLLM_SOURCE_DIR="${NEMOTRON_VLLM_SOURCE_DIR:-${NEMOTRON_REPO_ROOT}/vllm-v0.20.0}"

export NEMOTRON_MODEL_PATH="${NEMOTRON_MODEL_PATH:-${NEMOTRON_REPO_ROOT}/models/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4}"
export NEMOTRON_AUDIO_FIXTURE="${NEMOTRON_AUDIO_FIXTURE:-${NEMOTRON_REPO_ROOT}/media/cartesia-unicorn.wav}"

export NEMOTRON_VLLM_VENV="${NEMOTRON_VLLM_VENV:-${NEMOTRON_REPO_ROOT}/.venv-vllm-0.20.0-cu132}"
export NEMOTRON_VLLM_PYTHON="${NEMOTRON_VLLM_PYTHON:-${NEMOTRON_VLLM_VENV}/bin/python3}"
export NEMOTRON_VLLM_BIN="${NEMOTRON_VLLM_BIN:-${NEMOTRON_VLLM_VENV}/bin/vllm}"
export NEMOTRON_VLLM_MODEL="${NEMOTRON_VLLM_MODEL:-nemotron_3_nano_omni}"
export NEMOTRON_OMNI_MODEL="${NEMOTRON_OMNI_MODEL:-${NEMOTRON_VLLM_MODEL}}"
export NEMOTRON_OMNI_MAX_TOKENS="${NEMOTRON_OMNI_MAX_TOKENS:-1024}"
export NEMOTRON_OMNI_TEMPERATURE="${NEMOTRON_OMNI_TEMPERATURE:-0.2}"
export NEMOTRON_OMNI_TOP_K="${NEMOTRON_OMNI_TOP_K:-1}"

export NEMOTRON_VLLM_HOST="${NEMOTRON_VLLM_HOST:-0.0.0.0}"
export NEMOTRON_VLLM_PORT="${NEMOTRON_VLLM_PORT:-8000}"
export NEMOTRON_VLLM_BASE_URL="${NEMOTRON_VLLM_BASE_URL:-http://127.0.0.1:${NEMOTRON_VLLM_PORT}/v1}"
export NEMOTRON_VLLM_LOG="${NEMOTRON_VLLM_LOG:-${NEMOTRON_REPO_ROOT}/logs/rtx5090-vllm.log}"
export NEMOTRON_VLLM_PID="${NEMOTRON_VLLM_PID:-${NEMOTRON_REPO_ROOT}/logs/rtx5090-vllm.pid}"
export NEMOTRON_VLLM_START_TIMEOUT_SECS="${NEMOTRON_VLLM_START_TIMEOUT_SECS:-600}"

_DEFAULT_LIMIT_MM_PER_PROMPT='{"audio": 128}'

export NEMOTRON_VLLM_GPU_MEMORY_UTILIZATION="${NEMOTRON_VLLM_GPU_MEMORY_UTILIZATION:-0.75}"
export NEMOTRON_VLLM_MAX_MODEL_LEN="${NEMOTRON_VLLM_MAX_MODEL_LEN:-4096}"
export NEMOTRON_VLLM_MAX_NUM_SEQS="${NEMOTRON_VLLM_MAX_NUM_SEQS:-1}"
export NEMOTRON_VLLM_MAX_NUM_BATCHED_TOKENS="${NEMOTRON_VLLM_MAX_NUM_BATCHED_TOKENS:-4096}"
export NEMOTRON_VLLM_LIMIT_MM_PER_PROMPT="${NEMOTRON_VLLM_LIMIT_MM_PER_PROMPT:-${_DEFAULT_LIMIT_MM_PER_PROMPT}}"
export NEMOTRON_VLLM_ALLOWED_LOCAL_MEDIA_PATH="${NEMOTRON_VLLM_ALLOWED_LOCAL_MEDIA_PATH:-/}"
export NEMOTRON_VLLM_MM_ENCODER_ATTN_BACKEND="${NEMOTRON_VLLM_MM_ENCODER_ATTN_BACKEND:-TORCH_SDPA}"
export NEMOTRON_VLLM_KV_CACHE_MEMORY_BYTES="${NEMOTRON_VLLM_KV_CACHE_MEMORY_BYTES:-}"
export NEMOTRON_VLLM_KV_CACHE_DTYPE="${NEMOTRON_VLLM_KV_CACHE_DTYPE:-auto}"
export NEMOTRON_VLLM_SKIP_MM_PROFILING="${NEMOTRON_VLLM_SKIP_MM_PROFILING:-1}"
export NEMOTRON_VLLM_ENFORCE_EAGER="${NEMOTRON_VLLM_ENFORCE_EAGER:-1}"
export NEMOTRON_VLLM_REASONING_PARSER="${NEMOTRON_VLLM_REASONING_PARSER:-nemotron_v3}"
export NEMOTRON_VLLM_ENABLE_AUTO_TOOL_CHOICE="${NEMOTRON_VLLM_ENABLE_AUTO_TOOL_CHOICE:-1}"
export NEMOTRON_VLLM_TOOL_CALL_PARSER="${NEMOTRON_VLLM_TOOL_CALL_PARSER:-qwen3_coder}"
export NEMOTRON_VLLM_MOE_BACKEND="${NEMOTRON_VLLM_MOE_BACKEND:-cutlass}"
export NEMOTRON_VLLM_ATTENTION_BACKEND="${NEMOTRON_VLLM_ATTENTION_BACKEND:-}"
export NEMOTRON_VLLM_ENABLE_PREFIX_CACHING="${NEMOTRON_VLLM_ENABLE_PREFIX_CACHING:-1}"
export NEMOTRON_VLLM_MAMBA_CACHE_MODE="${NEMOTRON_VLLM_MAMBA_CACHE_MODE:-align}"
export NEMOTRON_VLLM_MAMBA_BACKEND="${NEMOTRON_VLLM_MAMBA_BACKEND:-triton}"

export VLLM_CONVERSATION_CACHE_MAX_ENTRIES="${VLLM_CONVERSATION_CACHE_MAX_ENTRIES:-8}"
export VLLM_CONVERSATION_CACHE_MAX_TOKENS="${VLLM_CONVERSATION_CACHE_MAX_TOKENS:-16384}"
export VLLM_CONVERSATION_CACHE_MIN_FREE_BLOCKS="${VLLM_CONVERSATION_CACHE_MIN_FREE_BLOCKS:-64}"
export VLLM_CONVERSATION_CACHE_TARGET_FREE_BLOCKS="${VLLM_CONVERSATION_CACHE_TARGET_FREE_BLOCKS:-128}"
