#!/usr/bin/env bash

_PLATFORM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
_REPO_ROOT="$(cd "${_PLATFORM_DIR}/../.." && pwd)"

export NEMOTRON_PLATFORM="${NEMOTRON_PLATFORM:-dgx_spark}"
export NEMOTRON_REPO_ROOT="${NEMOTRON_REPO_ROOT:-${_REPO_ROOT}}"
export NEMOTRON_VLLM_SOURCE_DIR="${NEMOTRON_VLLM_SOURCE_DIR:-${NEMOTRON_REPO_ROOT}/vllm-v0.20.0}"

export NEMOTRON_MODEL_PATH="${NEMOTRON_MODEL_PATH:-${NEMOTRON_REPO_ROOT}/models/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16}"
export NEMOTRON_AUDIO_FIXTURE="${NEMOTRON_AUDIO_FIXTURE:-${NEMOTRON_REPO_ROOT}/media/cartesia-unicorn.wav}"

export NEMOTRON_VLLM_VENV="${NEMOTRON_VLLM_VENV:-${NEMOTRON_REPO_ROOT}/.venv-vllm-spark}"
export NEMOTRON_VLLM_PYTHON="${NEMOTRON_VLLM_PYTHON:-${NEMOTRON_VLLM_VENV}/bin/python3}"
export NEMOTRON_VLLM_BIN="${NEMOTRON_VLLM_BIN:-${NEMOTRON_VLLM_VENV}/bin/vllm}"
export NEMOTRON_VLLM_MODEL="${NEMOTRON_VLLM_MODEL:-nemotron_3_nano_omni}"
export NEMOTRON_OMNI_MODEL="${NEMOTRON_OMNI_MODEL:-${NEMOTRON_VLLM_MODEL}}"
export NEMOTRON_OMNI_MAX_TOKENS="${NEMOTRON_OMNI_MAX_TOKENS:-1024}"
export NEMOTRON_OMNI_TEMPERATURE="${NEMOTRON_OMNI_TEMPERATURE:-0.2}"
export NEMOTRON_OMNI_TOP_K="${NEMOTRON_OMNI_TOP_K:-1}"

export NEMOTRON_VLLM_HOST="${NEMOTRON_VLLM_HOST:-0.0.0.0}"
export NEMOTRON_VLLM_PORT="${NEMOTRON_VLLM_PORT:-8000}"
export NEMOTRON_VLLM_BASE_URL="${NEMOTRON_VLLM_BASE_URL:-http://127.0.0.1:${NEMOTRON_VLLM_PORT}/v1}"
export NEMOTRON_VLLM_LOG="${NEMOTRON_VLLM_LOG:-${NEMOTRON_REPO_ROOT}/logs/dgx-spark-vllm.log}"
export NEMOTRON_VLLM_PID="${NEMOTRON_VLLM_PID:-${NEMOTRON_REPO_ROOT}/logs/dgx-spark-vllm.pid}"
export NEMOTRON_VLLM_START_TIMEOUT_SECS="${NEMOTRON_VLLM_START_TIMEOUT_SECS:-900}"

_DEFAULT_LIMIT_MM_PER_PROMPT='{"video": 0, "image": 1, "audio": 30}'
_DEFAULT_MEDIA_IO_KWARGS='{"video": {"fps": 2, "num_frames": 256}}'

export NEMOTRON_VLLM_GPU_MEMORY_UTILIZATION="${NEMOTRON_VLLM_GPU_MEMORY_UTILIZATION:-0.50}"
export NEMOTRON_VLLM_MAX_MODEL_LEN="${NEMOTRON_VLLM_MAX_MODEL_LEN:-32768}"
export NEMOTRON_VLLM_MAX_NUM_SEQS="${NEMOTRON_VLLM_MAX_NUM_SEQS:-1}"
export NEMOTRON_VLLM_MAX_NUM_BATCHED_TOKENS="${NEMOTRON_VLLM_MAX_NUM_BATCHED_TOKENS:-4096}"
export NEMOTRON_VLLM_LIMIT_MM_PER_PROMPT="${NEMOTRON_VLLM_LIMIT_MM_PER_PROMPT:-${_DEFAULT_LIMIT_MM_PER_PROMPT}}"
export NEMOTRON_VLLM_MEDIA_IO_KWARGS="${NEMOTRON_VLLM_MEDIA_IO_KWARGS:-${_DEFAULT_MEDIA_IO_KWARGS}}"
export NEMOTRON_VLLM_ALLOWED_LOCAL_MEDIA_PATH="${NEMOTRON_VLLM_ALLOWED_LOCAL_MEDIA_PATH:-${NEMOTRON_REPO_ROOT}}"
export NEMOTRON_VLLM_MM_ENCODER_ATTN_BACKEND="${NEMOTRON_VLLM_MM_ENCODER_ATTN_BACKEND:-TORCH_SDPA}"
export NEMOTRON_VLLM_KV_CACHE_MEMORY_BYTES="${NEMOTRON_VLLM_KV_CACHE_MEMORY_BYTES:-3G}"
export NEMOTRON_VLLM_KV_CACHE_DTYPE="${NEMOTRON_VLLM_KV_CACHE_DTYPE:-auto}"
export NEMOTRON_VLLM_SKIP_MM_PROFILING="${NEMOTRON_VLLM_SKIP_MM_PROFILING:-1}"
export NEMOTRON_VLLM_ENFORCE_EAGER="${NEMOTRON_VLLM_ENFORCE_EAGER:-1}"
export NEMOTRON_VLLM_REASONING_PARSER="${NEMOTRON_VLLM_REASONING_PARSER:-nemotron_v3}"
export NEMOTRON_VLLM_ENABLE_AUTO_TOOL_CHOICE="${NEMOTRON_VLLM_ENABLE_AUTO_TOOL_CHOICE:-1}"
export NEMOTRON_VLLM_TOOL_CALL_PARSER="${NEMOTRON_VLLM_TOOL_CALL_PARSER:-qwen3_coder}"
export NEMOTRON_VLLM_MOE_BACKEND="${NEMOTRON_VLLM_MOE_BACKEND:-triton}"
export NEMOTRON_VLLM_ENABLE_FLASHINFER_AUTOTUNE="${NEMOTRON_VLLM_ENABLE_FLASHINFER_AUTOTUNE:-0}"
export NEMOTRON_VLLM_ATTENTION_BACKEND="${NEMOTRON_VLLM_ATTENTION_BACKEND:-triton_attn}"
export NEMOTRON_VLLM_ENABLE_PREFIX_CACHING="${NEMOTRON_VLLM_ENABLE_PREFIX_CACHING:-1}"
export NEMOTRON_VLLM_MAMBA_CACHE_MODE="${NEMOTRON_VLLM_MAMBA_CACHE_MODE:-align}"
export NEMOTRON_VLLM_MAMBA_BACKEND="${NEMOTRON_VLLM_MAMBA_BACKEND:-triton}"

export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export HF_HUB_DISABLE_TELEMETRY="${HF_HUB_DISABLE_TELEMETRY:-1}"
export VLLM_DEEP_GEMM_WARMUP="${VLLM_DEEP_GEMM_WARMUP:-skip}"

export VLLM_CONVERSATION_CACHE_MAX_ENTRIES="${VLLM_CONVERSATION_CACHE_MAX_ENTRIES:-16}"
export VLLM_CONVERSATION_CACHE_MAX_TOKENS="${VLLM_CONVERSATION_CACHE_MAX_TOKENS:-262144}"
export VLLM_CONVERSATION_CACHE_MIN_FREE_BLOCKS="${VLLM_CONVERSATION_CACHE_MIN_FREE_BLOCKS:-128}"
export VLLM_CONVERSATION_CACHE_TARGET_FREE_BLOCKS="${VLLM_CONVERSATION_CACHE_TARGET_FREE_BLOCKS:-256}"
